###

POST http://localhost:3000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTdjZWJiNzg3MGU2ZTMwYTE5NmQ2OGYiLCJpYXQiOjE3Njk4MTYyNzMsImV4cCI6MTc2OTgxOTg3M30.98aWWJqCiLdYqBy3HNrCfRXNFZzTPOF01sSx-a5BXqU

{
    "title": "Reading a book2",
    "description": "A fascinating journey into the world of reading2."
}

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/6978b9c696f1736f495554fa

###

GET http://localhost:3000/post?sender=697a761cb0139ecd437a85ef

###

PUT http://localhost:3000/post/697d3e14fe9f53e9f54a500c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTdjZWJiNzg3MGU2ZTMwYTE5NmQ2OGYiLCJpYXQiOjE3Njk4MTYyNzMsImV4cCI6MTc2OTgxOTg3M30.98aWWJqCiLdYqBy3HNrCfRXNFZzTPOF01sSx-a5BXqU

{
  "title": "Reading a book",
  "description": "A fascinating journey into the world of readingnana."
}

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "6974d90b8a3dd0993516055c",
    "message": "Nice post! I like to read too.",
    "sender": "6790e0c8046777c6670a80e1"
}

###

GET http://localhost:3000/comment

###


GET http://localhost:3000/comment?postId=6974d90b8a3dd0993516055c

###

PUT http://localhost:3000/comment/6974d77bb9d6f59b625eede6
Content-Type: application/json

{
    "postId": "6974d90b8a3dd0993516055c",
    "message": "Nice post! I like to read too."
}

###

DELETE http://localhost:3000/comment/6974d77bb9d6f59b625eede6

###

PUT http://localhost:3000/user/6974d77bb9d6f59b625eede6
Content-Type: application/json

{
  "email": "example@gmail.com",
  "username": "exmaple_user",
  "password": "secret_password"
}

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "email": "example1@example.com",
    "username": "example1User",
    "password": "example1Pass"
}

###

GET http://localhost:3000/user

###

GET http://localhost:3000/user/697a78c9437f1b91bae9a42d

###
DELETE http://localhost:3000/user/6974d77bb9d6f59b625eede6


###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "newuser@example.comgaga",
    "username": "newuser",
    "password": "newpassword"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "newuser@example.com",
    "username": "newuser",
    "password": "newpassword"
}

