###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Reading a book",
    "description": "A fascinating journey into the world of reading.",
    "sender": "123"
}

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/6974d77bb9d6f59b625eede6

###

GET http://localhost:3000/post?sender=123