###

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Reading a book2",
    "description": "A fascinating journey into the world of reading2.",
    "sender": "697a78c9437f1b91bae9a42d"
}

###

GET http://localhost:3000/post

###

GET http://localhost:3000/post/6978b9c696f1736f495554fa

###

GET http://localhost:3000/post?sender=697a761cb0139ecd437a85ef

###

PUT http://localhost:3000/post/6974d77bb9d6f59b625eede6
Content-Type: application/json

{
  "title": "Reading a book",
  "description": "A fascinating journey into the world of reading.",
  "sender": "123"
}

###

POST http://localhost:3000/comment
Content-Type: application/json

{
    "postId": "6974d90b8a3dd0993516055c",
    "message": "Nice post! I like to read too."
}

###

GET http://localhost:3000/comment

###


GET http://localhost:3000/comment?postId=6974d90b8a3dd0993516055c

###

PUT http://localhost:3000/comment/6974d77bb9d6f59b625eede6
Content-Type: application/json

{
    "postId": "6974d90b8a3dd0993516055c",
    "message": "Nice post! I like to read too."
}

###

DELETE http://localhost:3000/comment/6974d77bb9d6f59b625eede6
